if(document.querySelector('.sidebar')){
  import('./deck-only-view.js?v=20260818-1');
}
if(document.querySelector('.header-actions')){
  import('./battle-link.js');
}
if(document.querySelector('.battle-page')){
  import('./battle-v2-ui.js');
}
